process_filter=true
process_name=aion2
tcp_reorder=false
setting_always_on_top=true
setting_always_on_top_type=A
setting_click_through=false
setting_boss_only=true
setting_player_display_mode=a, B
setting_damage_display_mode=A
setting_player_filter=A
setting_pin_self_to_top=false
setting_auto_target_only_self=false
setting_hide_unknown_nickname=true
setting_hide_unknown_npc=true
setting_group_skills=true
setting_show_boss_window=false
setting_boss_window_scale=100
setting_show_boss_debuffs=true
setting_boss_debuff_icon_size=27
setting_boss_window_refresh_ms=200
setting_show_boss_debuff_filter=false
setting_filtered_debuff_ids=
setting_show_only_my_debuffs=false
setting_show_buff_window=false
setting_buff_window_scale=100
setting_buff_icon_size=32
setting_buff_window_refresh_ms=200
setting_show_buff_filter=false
setting_filtered_buff_ids=
setting_boss_window_click_through=false
setting_buff_window_click_through=false
setting_use_tts=false
setting_tts_use_edge=true
setting_tts_voice=ko-KR-SunHiNeural
setting_tts_system_voice=Microsoft Heami Desktop
setting_tts_notify_on_start=true
setting_tts_notify_on_end=true
setting_tts_volume=100
setting_tts_rate=0
setting_tts_start_ment=온
setting_tts_end_ment=오프
setting_tts_filtered_buff_ids=
setting_show_capture_ready_overlay=true
setting_notification_confirmed=false
setting_self_color=
setting_elyos_color=
setting_asmodian_color=
setting_combat_power_color=
capture_mode=pcap
setting_window_scale=1.36
setting_tick_rate=1000
setting_header_bg_color=
setting_window_bg_color=
setting_border_color=
setting_font_family=
setting_font_size_name=12
setting_font_size_value=13
setting_show_col_job_icon=true
setting_show_col_name=true
setting_show_col_dps=true
setting_show_col_percent=true
setting_show_col_crit=true
setting_show_col_damage=true
setting_show_boss_icon=true
setting_show_ping_display=true
setting_column_order=JobIcon,Name,Dps,Percent,Crit,Damage
setting_text_opacity=1.00
setting_text_name_color=
setting_text_dps_color=
setting_text_percent_color=
setting_text_crit_color=
setting_text_damage_color=
setting_text_dropdown_color=
setting_text_combat_time_color=
setting_text_stat_dps_color=
setting_text_stat_damage_color=
setting_text_dropdown_bold=False
setting_text_combat_time_bold=True
setting_text_stat_dps_bold=False
setting_text_stat_damage_bold=False
setting_text_name_bold=False
setting_text_dps_bold=False
setting_text_percent_bold=False
setting_text_crit_bold=False
setting_text_damage_bold=False
setting_graph_enabled=False
setting_graph_self_only=False
setting_graph_interval=120
setting_graph_display_mode=A
setting_graph_cma_seconds=10
setting_graph_animated=False
setting_graph_style=a
setting_hotkey_toggle=
setting_hotkey_reset=0|Delete
setting_hotkey_click_through=
setting_hotkey_timer_start=
setting_hotkey_timer_stop=
setting_nickname_mask=A
setting_color_job_8=#FF4488FF
setting_color_job_12=#FF4488FF
setting_color_job_20=#FF44CC55
setting_color_job_16=#FF44CC55
setting_color_job_28=#FF8844DD
setting_color_job_24=#FF8844DD
setting_color_job_32=#FFFFCC33
setting_color_job_36=#FFFFCC33
window_left=-462
window_top=780
